### ISSUE TITLE
Unable to get other ERP data

### ISSUE THREAD

**Issue by TayWeiChong** [shaunkhoo/ltaer#2]
Dear Shaun, 

Thanks a lot for providing the API and sharing the source codes. I am trying to get the ERP rates from LTA Datamall, but i'm able to obtain the data for 2020-07-27. I tried to install your packages but failed because some packages were unable to overwrite, but managed to use your source code to get a set of data, which only contains 2020-07-27. May I ask how can I request for the date that I want in the script please? 

Thank you. 

Best regards,
Wei Chong

**Comment by shaunkhoo** [comment]
Hi Wei Chong, unfortunately there isn't a date parameter available in the API for ERP rates, so there is no way to request for the ERP rates from a specific date. This package is limited by what LTA makes available through the APIs so there is no way around this problem. Perhaps you can try emailing the maintainers at DataMall@lta.gov.sg?

**Comment by TayWeiChong** [comment]
Hi Shaun, thanks for your prompt reply and advice. Yup, I will write to them for assistance. Thank you. 

Best regards, 
Wei Chong

**Comment by shaunkhoo** [comment]
No problem!
